name: Auto-Merge Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install jq
      run: sudo apt-get install jq

    - name: Auto-Merge
      run: |
        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        TOKEN=$PERSONAL_ACCESS_TOKEN
        
        curl -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $TOKEN" \
          "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/merge"
